Experiment

diff --git a/bin/pipe/aml b/bin/pipe/aml
--- a/bin/pipe/aml
+++ b/bin/pipe/aml
@@ -23,6 +23,7 @@ submitted to AzureML with the matching name.
 EOF
 }
 
+exp=""
 while :; do
     case $1 in
         -h|--help) usage; exit ;;
@@ -33,6 +34,15 @@ while :; do
                 exit 1
             fi
             xargs=$2
+            shift
+            ;;
+        -e|--exp)
+            if [[ -z "$2" ]]; then
+                echo>&2 "Missing value for --exp."
+                usage >&2
+                exit 1
+            fi
+            exp=$2
             shift
             ;;
         *) break ;;
@@ -49,8 +59,27 @@ pipeline=$1
 
 bin/chkenv "AZUREML_WORKSPACE" "AZUREML_RESOURCE_GROUP"
 
-source bin/lib.sh  # import: prep_run, run_aml
+source bin/utils/lib.sh  # import: prep_run, run_aml
 read -r run_name run_dir <<< "$(prep_run "$pipeline")"
 bin/pipe/iso "$pipeline" "$run_dir" > /dev/null
 
-run_aml "$run_name" "$run_dir" "$pipeline.yaml" "$xargs"
+run_args=("$run_name" "$run_dir" "$pipeline.yaml" "$xargs")
+if [[ -z "$exp" ]]; then
+    # If no experiment is provided, run the job from current branch
+    run_aml "${run_args[@]}"
+    exit
+fi
+
+bin/chkenv "EXPERIMENTS_BRANCH"
+
+commit_id=$(bin/utils/prep-exp --exp-ref "$EXPERIMENTS_BRANCH" "$exp")
+curr_branch=$(git rev-parse --abbrev-ref HEAD)
+git checkout "$EXPERIMENTS_BRANCH"
+
+if run_aml "${run_args[@]}"; then
+    # Push commit to experiment branch only if job submission succeeded
+    git push "origin" "$commit_id:$EXPERIMENTS_BRANCH"
+fi
+
+# Restore working directory to the original branch.
+git checkout "$curr_branch"
