Bump uv and update local

diff --git a/bin/exp/pkg b/bin/exp/pkg
--- a/bin/exp/pkg
+++ b/bin/exp/pkg
@@ -1,45 +1,47 @@
 #!/usr/bin/env bash
-#? Package artifacts for an experiment run in a separate directory
+#? Isolate artifacts for an package run in a separate directory
 
 set -eo pipefail
 cd "$(dirname "$0")/../.."
 
 function usage {
     cat<<EOF
-Package artifacts for an experiment run in a separate directory
+Isolate artifacts for an package run in a separate directory
 
-Usage: $0 EXPERIMENT RUN_NAME
+Usage: $0 PACKAGE RUN_NAME
 
 Options:
     -h, --help            Show this help message and exit
 
 Arguments:
-  EXPERIMENT  Directory of the experiment relative to "$CODE_PATH"
+  PACKAGE     Directory of the package relative to "$PKGS_PATH"
   RUN_NAME    Name of the run
 
-The goal is to package the absolute minimum to run an experiment. This aims to
-make the experiment reproducible and portable as well as easy to reason about in
+The goal is to isolate the absolute minimum to run a package. This aims to
+make the run reproducible and portable as well as easy to reason about in
 the future.
 
-The run directory will be created in "$RUNS_PATH/EXPERIMENT/RUN_NAME".
-The run directory will contain all files inside EXPERIMENT and will
-add the shared code and the environment files. Thus, the final structure:
+The run directory will be created in "$RUNS_PATH/PACKAGE/RUN_NAME".
+The run directory will contain all files inside PACKAGE and will
+add the 'shared' code and the environment files. Thus, the final structure:
   <run_name>
   ├── .amlignore
   ├── azure-ml-job.yaml
   ├── shared/
+  ├── tests/
   ├── environment/
   │   ├── Dockerfile
   │   └── requirements.txt
-  └── <experiment>
-      ├── tests/
-      ├── main.py
+  └── <package>
+      ├── __main__.py
       └── ...
 
 The requirements.txt will contain only the dependencies specified for the
-experiment.
+package.
 EOF
 }
+
+bin/chkenv "PKGS_PATH" "RUNS_PATH"
 
 while :; do
     case $1 in
@@ -50,35 +52,32 @@ while :; do
 done
 
 if [ $# -ne 2 ]; then
-    echo>&2 "Both EXPERIMENT and RUN_NAME required."
+    echo>&2 "Both PACKAGE and RUN_NAME required."
     usage>&2
     exit 1
 fi
 
-source bin/env container.env
-bin/chkenv "CODE_PATH" "RUNS_PATH"
-
-experiment=$1
+package=$1
 run_name=$2
-if [[ ! -d "$CODE_PATH/$experiment" ]]; then
-    echo>&2 "Experiment directory '$CODE_PATH/$experiment' does not exist."
+if [[ ! -d "$PKGS_PATH/$package" ]]; then
+    echo>&2 "Package directory '$PKGS_PATH/$package' does not exist."
     exit 1
 fi
 
 # create run directory
-run_dir="$RUNS_PATH/$experiment/$run_name"
+run_dir="$RUNS_PATH/$package/$run_name"
 mkdir -p "$run_dir"
 
-# copy experiment code and common code to run directory
-cp -r "$CODE_PATH/$experiment/src/." "$run_dir"
-cp -r "$CODE_PATH/shared/src/shared" "$run_dir"
+# copy package code and common code to run directory
+cp -r "$PKGS_PATH/$package/src/." "$run_dir"
+cp -r "$PKGS_PATH/shared/src/shared" "$run_dir"
 
 # copy artifacts to build environment
 docker_context="$run_dir/environment"
 mkdir -p "$docker_context"
 uv export --quiet \
     --output-file "$docker_context/requirements.txt" \
-    --package "$experiment" \
+    --package "$package" \
     --no-hashes \
     --no-emit-workspace
 
